# Generated by Django 5.2.1 on 2025-06-01 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon1', models.CharField(max_length=150, unique=True)),
                ('pokemon2', models.CharField(max_length=150, unique=True)),
                ('route', models.CharField(max_length=150, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soullink', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
