# Generated by Django 5.2.1 on 2025-06-02 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_soullink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soullink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soullink', to=settings.AUTH_USER_MODEL),
        ),
    ]
