# Generated by Django 5.2.1 on 2025-06-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_soullink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soullink',
            name='pokemon1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='soullink',
            name='pokemon2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='soullink',
            name='route',
            field=models.CharField(max_length=150),
        ),
    ]
